"""API and integration layer for ultra-robust XML parsing.

This module provides progressive disclosure API with simple defaults, advanced
configuration, and seamless integration capabilities.
"""

from .parser import (
    UltraRobustXMLParser,
    parse,
    parse_file,
    parse_string,
)
from .adapters import (
    IntegrationAdapter,
    AdapterType,
    ConversionDirection,
    AdapterMetadata,
    ConversionResult,
    register_adapter,
    get_adapter,
    list_available_adapters,
    get_adapters_by_type,
    validate_adapter_compatibility,
    LxmlAdapter,
    BeautifulSoupAdapter,
    ElementTreeAdapter,
    PandasAdapter,
    FlaskAdapter,
    DjangoAdapter,
    FastAPIAdapter,
    PluginMetadata,
    PluginAdapter,
    discover_plugins,
    load_plugin,
    unload_plugin,
    list_loaded_plugins,
    get_plugin_config,
    get_equivalent_adapter,
    create_legacy_wrapper,
    analyze_migration_code,
    convert_migration_code,
    create_migration_guide,
    BenchmarkResult,
    run_performance_benchmark,
    generate_performance_report,
    analyze_adapter_performance,
    check_performance_regressions,
)

__all__ = [
    "UltraRobustXMLParser",
    "parse",
    "parse_file",
    "parse_string",
    "IntegrationAdapter",
    "AdapterType",
    "ConversionDirection",
    "AdapterMetadata",
    "ConversionResult",
    "register_adapter",
    "get_adapter",
    "list_available_adapters",
    "get_adapters_by_type",
    "validate_adapter_compatibility",
    "LxmlAdapter",
    "BeautifulSoupAdapter",
    "ElementTreeAdapter",
    "PandasAdapter",
    "FlaskAdapter",
    "DjangoAdapter",
    "FastAPIAdapter",
    "PluginMetadata",
    "PluginAdapter",
    "discover_plugins",
    "load_plugin",
    "unload_plugin",
    "list_loaded_plugins",
    "get_plugin_config",
    "get_equivalent_adapter",
    "create_legacy_wrapper",
    "analyze_migration_code",
    "convert_migration_code",
    "create_migration_guide",
    "BenchmarkResult",
    "run_performance_benchmark",
    "generate_performance_report",
    "analyze_adapter_performance",
    "check_performance_regressions",
]
